/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignmentfol;

import javax.swing.text.PasswordView;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author modsyan
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbFirstName = new javax.swing.JLabel();
        tfFristName = new javax.swing.JTextField();
        vmFirstName = new javax.swing.JLabel();
        tfLastName = new javax.swing.JTextField();
        vmLastName = new javax.swing.JLabel();
        lbLastName = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        vmEmail = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        vmPassword = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        vmJobExperince = new javax.swing.JLabel();
        lbJobExperince = new javax.swing.JLabel();
        tfEducation = new javax.swing.JTextField();
        vmEducation = new javax.swing.JLabel();
        lbEdcuation = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfJobExperince = new javax.swing.JTextArea();
        btnSendEmail = new javax.swing.JButton();
        tfPassword = new javax.swing.JPasswordField();
        vmBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setText("Sign Up");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(313, 313, 313))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        lbFirstName.setFont(new java.awt.Font("JetBrainsMono Nerd Font", 0, 14)); // NOI18N
        lbFirstName.setText("First Name");

        tfFristName.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        tfFristName.setToolTipText("Enter your First Email");
        tfFristName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFristNameActionPerformed(evt);
            }
        });

        vmFirstName.setBackground(new java.awt.Color(255, 0, 0));
        vmFirstName.setFont(new java.awt.Font("Iosevka Nerd Font", 2, 10)); // NOI18N
        vmFirstName.setForeground(new java.awt.Color(255, 51, 51));
        vmFirstName.setText(" ");

        tfLastName.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        tfLastName.setToolTipText("Enter Your Last Name");
        tfLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLastNameActionPerformed(evt);
            }
        });

        vmLastName.setBackground(new java.awt.Color(255, 0, 0));
        vmLastName.setFont(new java.awt.Font("Iosevka Nerd Font", 2, 10)); // NOI18N
        vmLastName.setForeground(new java.awt.Color(255, 51, 51));
        vmLastName.setText(" ");

        lbLastName.setFont(new java.awt.Font("JetBrainsMono Nerd Font", 0, 14)); // NOI18N
        lbLastName.setText("Last Name");

        tfEmail.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        tfEmail.setToolTipText("Enter Your Email");
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        vmEmail.setBackground(new java.awt.Color(255, 0, 0));
        vmEmail.setFont(new java.awt.Font("Iosevka Nerd Font", 2, 10)); // NOI18N
        vmEmail.setForeground(new java.awt.Color(255, 51, 51));
        vmEmail.setText(" ");

        lbEmail.setFont(new java.awt.Font("JetBrainsMono Nerd Font", 0, 14)); // NOI18N
        lbEmail.setText("Email");

        vmPassword.setBackground(new java.awt.Color(255, 0, 0));
        vmPassword.setFont(new java.awt.Font("Iosevka Nerd Font", 2, 10)); // NOI18N
        vmPassword.setForeground(new java.awt.Color(255, 51, 51));
        vmPassword.setText("   ");

        lbPassword.setFont(new java.awt.Font("JetBrainsMono Nerd Font", 0, 14)); // NOI18N
        lbPassword.setText("Password");

        vmJobExperince.setBackground(new java.awt.Color(255, 0, 0));
        vmJobExperince.setFont(new java.awt.Font("Iosevka Nerd Font", 2, 10)); // NOI18N
        vmJobExperince.setForeground(new java.awt.Color(255, 51, 51));
        vmJobExperince.setText(" ");

        lbJobExperince.setFont(new java.awt.Font("JetBrainsMono Nerd Font", 0, 14)); // NOI18N
        lbJobExperince.setText("Job Experince");

        tfEducation.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        tfEducation.setToolTipText("Enter Your Collage Here");
        tfEducation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEducationActionPerformed(evt);
            }
        });

        vmEducation.setBackground(new java.awt.Color(255, 0, 0));
        vmEducation.setFont(new java.awt.Font("Iosevka Nerd Font", 2, 10)); // NOI18N
        vmEducation.setForeground(new java.awt.Color(255, 51, 51));
        vmEducation.setText(" ");

        lbEdcuation.setFont(new java.awt.Font("JetBrainsMono Nerd Font", 0, 14)); // NOI18N
        lbEdcuation.setText("Education");

        tfJobExperince.setColumns(20);
        tfJobExperince.setRows(5);
        tfJobExperince.setToolTipText("List Of All Job Expretires here");
        jScrollPane1.setViewportView(tfJobExperince);

        btnSendEmail.setText("Send Email");
        btnSendEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendEmailActionPerformed(evt);
            }
        });

        tfPassword.setToolTipText("Enter Your Password Here");

        vmBtn.setBackground(new java.awt.Color(255, 0, 0));
        vmBtn.setFont(new java.awt.Font("Iosevka Nerd Font", 2, 10)); // NOI18N
        vmBtn.setForeground(new java.awt.Color(0, 204, 51));
        vmBtn.setText("               ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbJobExperince)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbEmail)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(vmEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfFristName, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbFirstName))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vmFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vmJobExperince, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                    .addComponent(lbLastName)
                                    .addComponent(lbPassword)
                                    .addComponent(tfEducation)
                                    .addComponent(lbEdcuation)
                                    .addComponent(tfPassword)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(vmPassword)
                                        .addGap(235, 235, 235))
                                    .addComponent(vmEducation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vmLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSendEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(vmBtn)
                        .addGap(325, 325, 325))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbLastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vmLastName))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbFirstName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFristName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vmFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(vmEmail))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vmPassword)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEdcuation)
                    .addComponent(lbJobExperince))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfEducation, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vmEducation)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vmJobExperince)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnSendEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vmBtn)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfFristNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFristNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFristNameActionPerformed

    private void tfLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLastNameActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void tfEducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEducationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEducationActionPerformed

    private void btnSendEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendEmailActionPerformed
        // TODO add your handling code here:
        Properties properties = new Properties();
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("email.smtp.host", "smtp.gmail.com");
        properties.put("email.smtp.port", "587");
       
     

        
        String firstName = tfFristName.getText();
        String lastName = tfLastName.getText();
        String email = tfEmail.getText();
        char[] password = tfPassword.getPassword();
        String education = tfEducation.getText();
        String jobExperince = tfJobExperince.getText();
        
        bool isValidFirstName, isValidLastName, isValidPassword, isValidPassword;
        
        if (firstName.length() < 4) {
            vmFirstName.setText("Wrong Name, Must Be Greater Than 3 Characters");
        } else {
            isValidFirstName = true;
        }
        
        if (lastName.length() < 4) {
            vmLastName.setText("Wrong Name, must be Grater Than # Characters");
        } else {
            isValidLastName = true;
        }
        
        for (int i =0 ;i < password.length; i++) {
            if(Character.isUpperCase(password[i])) {
                isValidPassword = true;
            }
        }
        
        
        if (isValidFirstName && isValidLastName && isValidPassword) {
            JOptionPane.showMessageDialog(null, "Successful Message Has been Sent.");
        }
        
    }//GEN-LAST:event_btnSendEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEdcuation;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbFirstName;
    private javax.swing.JLabel lbJobExperince;
    private javax.swing.JLabel lbLastName;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JTextField tfEducation;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfFristName;
    private javax.swing.JTextArea tfJobExperince;
    private javax.swing.JTextField tfLastName;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JLabel vmBtn;
    private javax.swing.JLabel vmEducation;
    private javax.swing.JLabel vmEmail;
    private javax.swing.JLabel vmFirstName;
    private javax.swing.JLabel vmJobExperince;
    private javax.swing.JLabel vmLastName;
    private javax.swing.JLabel vmPassword;
    // End of variables declaration//GEN-END:variables
}
